-- Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal
-- numbers are:

-- 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

-- It can be seen that P4 + P7 = 22 + 70 = 92 = P8.
-- However, their difference, 70 − 22 = 48, is not pentagonal.

-- Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference
-- are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

import MyLib_haskell

generatePentagonNum :: Int -> Int
generatePentagonNum n = (3 * (n*n) - n) `div` 2

brute = minimum [d | a <- num, b <- num, a>b, let d = a-b, isPentagonNum d, isPentagonNum (a+b)]
  where
    num = map generatePentagonNum [1000..10000]

main = print brute
